/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ShaderMapper {
    'fragment': string;
    'images': string;
    'vertex': string;
  }
}

declare global {


  interface HTMLShaderMapperElement extends Components.ShaderMapper, HTMLStencilElement {}
  var HTMLShaderMapperElement: {
    prototype: HTMLShaderMapperElement;
    new (): HTMLShaderMapperElement;
  };
  interface HTMLElementTagNameMap {
    'shader-mapper': HTMLShaderMapperElement;
  }
}

declare namespace LocalJSX {
  interface ShaderMapper {
    'fragment'?: string;
    'images'?: string;
    'vertex'?: string;
  }

  interface IntrinsicElements {
    'shader-mapper': ShaderMapper;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'shader-mapper': LocalJSX.ShaderMapper & JSXBase.HTMLAttributes<HTMLShaderMapperElement>;
    }
  }
}


